#docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile-slim -t bnhf/ws-scrcpy:test2 . --push --no-cache
FROM alpine:latest AS builder
ADD . /ws-scrcpy
RUN apk add --no-cache nodejs npm python3 make g++
WORKDIR /ws-scrcpy
RUN npm install
RUN npm run dist
WORKDIR dist
RUN npm install

FROM alpine:latest AS runner
LABEL maintainer="The Slayer <slayer@technologydragonslayer.com>"

RUN apk add --no-cache android-tools npm
COPY --from=builder /ws-scrcpy/dist /root/ws-scrcpy

WORKDIR /root/ws-scrcpy
CMD ["npm", "start"]